### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by bplommer** [armanbilge/oxidized#11]
I wanted to have a go at actually using this and saw a release was never cut - any objection if I do so?

**Comment by armanbilge** [comment]
You can try, the build infra may need to be refreshed.

Alternatively there is a snapshot of the latest commit, maybe that would work for you?

https://s01.oss.sonatype.org/content/repositories/snapshots/com/armanbilge/oxidized_3/0.1-412be9c-SNAPSHOT/

**Comment by zarthross** [comment]
A release of this would be awesome, is there anything I can do to press this forward?

**Comment by armanbilge** [comment]
@zarthross I could do an v0.0.1, I wouldn't say this library is particularly mature. What's the specific thing you want to use from it?

**Comment by zarthross** [comment]
My interest is largely because of this issue, https://github.com/typelevel/cats-effect/issues/1821 

What I'd like access to without a lot of copy/pasta is https://github.com/armanbilge/oxidized/blob/412be9cd0a60b901fd5f9157ea48bda8632c5527/core/src/main/scala/oxidized/instances/io.scala#L34C1-L43C6

**Comment by armanbilge** [comment]
https://github.com/armanbilge/oxidized/releases/tag/v0.1.0
